<a href="https://colab.research.google.com/github/SWATHI-MUTHU/Python_Workout_Notes/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [ ]:
l=[1,2,3,4,5]

In [ ]:
type(l)

list

In [ ]:
arr =np.array(l)


In [ ]:
type(arr)

numpy.ndarray

In [ ]:
#1)can we do replace a particular element in an array?
arr

array([1, 2, 3, 4, 5])

In [ ]:
arr[0]=90

In [ ]:
arr

array([90,  2,  3,  4,  5])

In [ ]:
#2)How  do we see the dimension ans size of an array?
arr.ndim

1

In [ ]:
arr.size

5

In [ ]:
#3) How to create multi dimensional array?
arr1  =np.array(([2,3,4],[5,6,7]))

In [ ]:
arr1.ndim

2

In [ ]:
arr1.size

6

In [ ]:
#4)coping an numpy array
arr2=np.copy(arr1)

In [ ]:
#5)what is the special aspect in numpy range functionality?
np.arange(0.4,10.4,0.2)

array([ 0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,  2.2,  2.4,
        2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,  4.4,  4.6,
        4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,  6.6,  6.8,
        7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,  8.8,  9. ,
        9.2,  9.4,  9.6,  9.8, 10. , 10.2])

In [ ]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [ ]:
np.logspace(1,4,20,base=10)

array([   10.        ,    14.38449888,    20.69138081,    29.76351442,
          42.81332399,    61.58482111,    88.58667904,   127.42749857,
         183.29807108,   263.66508987,   379.26901907,   545.55947812,
         784.75997035,  1128.83789168,  1623.77673919,  2335.72146909,
        3359.81828628,  4832.93023857,  6951.92796178, 10000.        ])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.ones((3,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [4]:
#create a diagional maatrix havig value of 1 with a size 3*3
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
np.random.rand(2,3)

array([[0.78490308, 0.35574612, 0.84400406],
       [0.68460788, 0.13483096, 0.07522607]])

In [8]:
np.random.randn(2,3)

array([[ 2.52381885,  0.13890951, -1.45499987],
       [ 0.54650379,  0.43822606, -0.92888154]])

In [11]:
np.random.randint(1,10,(2,4))

array([[2, 4, 4, 3],
       [6, 1, 3, 4]])

In [18]:
arr1=np.random.randint(1,10,(2,3))

In [19]:
arr1

array([[4, 5, 9],
       [7, 1, 9]])

In [22]:
arr1.reshape(3,2)

array([[4, 5],
       [9, 7],
       [1, 9]])

In [20]:
arr1.shape

(2, 3)

In [24]:
arr1=np.random.randint(1,10,(2,3))
arr2=np.random.randint(1,10,(2,3))

In [26]:
arr1*arr2

array([[21, 28, 21],
       [ 3, 27, 24]])

In [28]:
np.sin(arr1)

array([[ 0.6569866 , -0.7568025 ,  0.14112001],
       [ 0.14112001,  0.14112001, -0.2794155 ]])

In [30]:
np.tan(arr2)

array([[-0.14254654,  0.87144798,  0.87144798],
       [ 1.55740772, -0.45231566,  1.15782128]])

In [32]:
np.power(arr1,3)

array([[343,  64,  27],
       [ 27,  27, 216]])

In [33]:
np.mean(arr1)

4.333333333333333

In [36]:
np.median(arr1)

3.5

In [38]:
np.var(arr1)

2.5555555555555554